<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <meta http-equiv="X-UA-Compatible" content="ie=edge">
        <title>Email</title>

    </head>
    <body style="font-family:'verdana'; margin:10px;background-color:#252423 ">
            <h1 style="text-align:center; color:white;">Automation</h1>
            <p style="color:white;">Hi Oliver,</p>
            <p style="color:white;">We want to inform you that we have deleted the completed or withdrawn jobs that exceeded 3 months from the day they were returned.</p>
            <p style=" font-style:italic;color:white;margin-top:50px;">This is autogenerated email.</p>
    </body>
</html>
