<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <meta http-equiv="X-UA-Compatible" content="ie=edge">
        <title>Email</title>

    </head>
    <body style="font-family:'verdana'; margin:10px;background-color:#252423 ">
            <h1 style="text-align:center; color:white;">Automation</h1>
            <p style="color:white;">Hi Oliver,</p>
            <p style="color:white;">We wanted to inform you about the current status of the jobs.</p>
            @if (empty($details['wjn_priority']) && empty($details['ojn_priority']) && empty($details['wjn_routine']) && empty($details['ojn_routine']))
                <div style="margin-top:50px;background-color:#252423">
                    <p style="color: white">No warning and overdue jobs</p>
                </div>
            @endif
            @if (!empty($details['wjn_priority']))
            <div style="margin-top:50px;background-color:#252423">
                <h3 style="color:orange;">Warning Jobs - Priority</h3>
                <table style="background-color:#252423">
                    <thead>
                        <tr>
                            <th style="color:orange;" colspan="12">Job Numbers</th>
                        </tr>
                    </thead>
                    <tbody>
                        @foreach($details['wjn_priority'] as $index => $detail)
                            <td style="color:white;">{{ $detail }}</td>
                            @if(($index + 1) % 12 == 0)
                                </tr><tr>
                            @endif
                        @endforeach
                    </tbody>
                </table>
            </div>
            @endif

            @if (!empty($details['ojn_priority']))
            <div style="margin-top:50px;background-color:#252423">
                <h3 style="color:red;">Overdue Jobs - Priority</h3>
                <table style="background-color:#252423">
                    <thead>
                        <tr>
                            <th style="color:red;" colspan="12">Job Numbers</th>
                        </tr>
                    </thead>
                    <tbody>
                        @foreach($details['ojn_priority'] as $index => $detail)
                            <td style="color:white;">{{ $detail }}</td>
                            @if(($index + 1) % 12 == 0)
                                </tr><tr>
                            @endif
                        @endforeach
                    </tbody>
                </table>
            </div>
            @endif
            @if (!empty($details['wjn_routine']))
            <div style="margin-top:50px;background-color:#252423">
                <h3 style="color:orange;">Warning Jobs - Routine</h3>
                <table style="background-color:#252423">
                    <thead>
                        <tr>
                            <th style="color:orange;" colspan="12">Job Numbers</th>
                        </tr>
                    </thead>
                    <tbody>
                        @foreach($details['wjn_routine'] as $index => $detail)
                            <td style="color:white;">{{ $detail }}</td>
                            @if(($index + 1) % 12 == 0)
                                </tr><tr>
                            @endif
                        @endforeach
                    </tbody>
                </table>
            </div>
            @endif

            @if (!empty($details['ojn_routine']))
                <div style="margin-top:50px;background-color:#252423">
                    <h3 style="color:red;">Overdue Jobs - Routine</h3>
                    <table style="background-color:#252423">
                        <thead>
                            <tr>
                                <th style="color:red;" colspan="12">Job Numbers</th>
                            </tr>
                        </thead>
                        <tbody>
                            @foreach($details['ojn_routine'] as $index => $detail)
                                <td style="color:white;">{{ $detail }}</td>
                                @if(($index + 1) % 12 == 0)
                                    </tr><tr>
                                @endif
                            @endforeach
                        </tbody>
                    </table>
                </div>
            @endif
            <p style=" font-style:italic;color:white;margin-top:50px;">This is autogenerated email.</p>


    </body>
</html>
